### ISSUE TITLE
RFE Can we get a nodejs6 build

### ISSUE THREAD

**Issue by kbsingh** [sclorg/s2i-nodejs-container#117]
Hi

For a couple of efforts bootstrapping up right now, we are looking at nodejs 6 by way of starting the code on. To support this stack in ci, staging and prod environments, it would be great to get a suiteable supported container for nodejs6.

**Comment by kasicka** [comment]
rh-nodejs6 won't be released in RHSCL 2.3, so there won't be *officially supported* nodejs6 container for a while IMO.

**Comment by bparees** [comment]
In the meantime you can check out https://github.com/ryanj/origin-s2i-nodejs which provides packaging of the latest nodejs releases.

**Comment by pkubatrh** [comment]
Nodejs version 6 is available now so I guess this can be closed.
