### ISSUE TITLE
Build Angular2 image

### ISSUE THREAD

**Issue by cbeldacap** [sclorg/s2i-nodejs-container#135]
Hello,

I'm trying to use your `s2i-nodejs-container` image to build a Angular2 image (from a git repository of a project of mine).

There is a moment when the building fails saying that there are problems with "npm commands".

Have you heard about any other issue in the same case?

Thank you so much in advance,
Cristóbal

**Comment by kasicka** [comment]
Can you post the log and a link to your repo, please?

**Comment by cbeldacap** [comment]
first of all, thnx for the quick feed-back

My repo is just about a standard angular2 project created by `ng new [project]`. 
https://github.com/cbeldacap/pruebang2

This is the error I have after typing (being **s2i-nodejs** the image built from this repo from `/4` folder) :
`./s2i.exe   https://github.com/cbeldacap/pruebang2   s2i-nodej   myng2image`

![image](https://cloud.githubusercontent.com/assets/20857839/23171199/20dcaa02-f852-11e6-82b6-a7be3ccbb79a.png)

**Comment by kasicka** [comment]
The repository returns 404.
Building different project works for me/fails because of unsatisfied dependencies in the project.

**Comment by phracek** [comment]
Sorry, we do not have capacity to fix this issue. In case you really need it or if it is still valid please re-open this issue.
