### ISSUE TITLE
Adding yarn support into nodejs images

### ISSUE THREAD

**Issue by andrewklau** [sclorg/s2i-nodejs-container#137]
Yarn is a lot more predictable and has better performance over NPM https://blog.heroku.com/yarn-deterministic-dependency-resolution

It'd be good if we could package yarn into the nodejs images and only use it if a yarn.lock file exists

**Comment by fndejong** [comment]
I modified the NodeJS 8 Dockerfile to (safely) install Yarn 1.5.1 and updated the S2I assembly file to run yarn install, instead of npm install, when a yarn.lock is present.

I will create a PR later today. A question that remains: can we rely on the yarn.lock always being available, or should we add an additional flag to force the use of yarn?

**Comment by omron93** [comment]
I think first step have to be to add `yarn` in Red Hat Software Collections. You can report bug (http://bugzilla.redhat.com/) which asks it. @notroj Where to get more information about adding new SW into RHSCL?

**Comment by cdrage** [comment]
@phracek What is the progress of this? I'm trying to run https://github.com/gothinkster/vue-realworld-example-app but keep encountering issues with not being able to use Yarn.

Funny enough... I'm actually able to get somewhat there when setting up an environment variable of `YARN_ENABLED=true` for s2i before deploying.. 

Was this ever implemented, and if so, is there any documentation anywhere?

**Comment by terbolous** [comment]
Couldn't yarn be supported in the s2i scripts regardless? 

We simply install yarn with npm on our custom image, but would prefer if we didn't have to maintain the s2i scripts as well.

Wrapping it in a `YARN_ENABLED` environment variable or similar could let it be up to the user/read to get yarn installed first

**Comment by phracek** [comment]
@andrewklau Can you please create a pull request with yarn support to this container repository?

**Comment by phracek** [comment]
We do not have resources to fix it. The issue is 'stale'. Feel free to re-open it and file PR.
