### ISSUE TITLE
Failed to kill container

### ISSUE THREAD

**Issue by DMevada** [sclorg/s2i-nodejs-container#138]
Hi,

Not sure if this is the right place to post this, if it's not, please let me know where to open this issue.

I am trying out the example given in 4/README.md.
My system is CentOS 7.2, and here are the steps that I took to generate the docker container:

1) make build TARGET=centos7 VERSION=4
2) ../s2i build https://github.com/sclorg/s2i-nodejs-container.git --context-dir=4/test/test-app/ centos/nodejs-44-centos7 nodejs-sample-app --loglevel 5

Step 1 executes fine, but step 2 is unable to kill a container.
Here is the output of step 2:

![screen shot 2017-03-24 at 4 46 37 pm](https://cloud.githubusercontent.com/assets/3958578/24317098/7dbaff2c-10b1-11e7-9c07-a09cc071425d.png)

![screen shot 2017-03-24 at 4 47 25 pm](https://cloud.githubusercontent.com/assets/3958578/24317115/9cc13738-10b1-11e7-9b2e-437770e3797d.png)

How do I get past this error?
My docker version is: Docker version 17.03.0-ce, build 60ccb22

**Comment by bparees** [comment]
1) the issue should be opened against the openshift/source-to-image repository
2) when you do so, please provide the full log output (preferably as a gist, not a screenshot).  I can't actually tell from your output that the failure is related to s2i not being able to kill the container, but i don't think it is.

**Comment by DMevada** [comment]
Alright, thanks for the update
