### ISSUE TITLE
Extend base Node.js image

### ISSUE THREAD

**Issue by Dec-** [sclorg/s2i-nodejs-container#145]
Hi,

how can i extend base Node.js 6 Image?
registry.access.redhat.com/rhscl/nodejs-6-rhel7

With Oracle/DB2 drivers?

**Comment by bparees** [comment]
Write a Dockerfile that is
```
FROM registry.access.redhat.com/rhscl/nodejs-6-rhel7
ADD [oracle drivers]
```

**Comment by Dec-** [comment]
Thx for answer but when i do something like this:

```
FROM registry.access.redhat.com/rhscl/nodejs-6-rhel7

RUN npm install -g bower
```
I get this error.
```
Sending build context to Docker daemon 10.24 kB
Step 1/2 : FROM registry.access.redhat.com/rhscl/nodejs-6-rhel7
 ---> 7821c65f5dbc
Step 2/2 : RUN npm install -g bower
 ---> Running in e9e4c56b330a
/bin/sh: npm: command not found
The command '/bin/sh -c npm install -g bower' returned a non-zero code: 127
```

**Comment by bparees** [comment]
npm is part of an scl package, so you need to enable the scl package before running those commands:
https://github.com/sclorg/s2i-nodejs-container/blob/master/6/root/opt/app-root/etc/scl_enable#L3

you also may need to switch back to "USER root" since by default those commands will run as user 1001 which may or may not have the permissions you need.

**Comment by Dec-** [comment]
Hi.
it's still the same :)

```
FROM registry.access.redhat.com/rhscl/nodejs-6-rhel7 
RUN unset BASH_ENV PROMPT_COMMAND ENV
RUN source scl_source enable rh-nodejs6
USER 1001
RUN npm install -g bower
```

Am i doing it right?

**Comment by omron93** [comment]
> RUN unset BASH_ENV PROMPT_COMMAND ENV

If you don't have special plans with this, it should be still set in resulted image. This allows accessing of programs from Software Collection without doing `scl enable` -- ONLY when running `bash`!

> RUN source scl_source enable rh-nodejs6
USER 1001
> RUN npm install -g bower

First RUN basically sets some environmental variables. Docker creates new layer and second RUN has clean environment.

So you could have
```
USER 1001
RUN source scl_source enable rh-nodejs6 && npm install -g bower
```
preferably
```
USER 1001
RUN scl enable rh-nodejs6 -- npm install -g bower
```

Or you could use fact that SCL is automatically enabled in bash
```
FROM registry.access.redhat.com/rhscl/nodejs-6-rhel7
RUN bash -c "npm install -g bower"
```

**Comment by Dec-** [comment]
Thank you! It works.
So let's say we want add something to base/builder s2i node.js image. Bower,
Is this recomanded way to do it?

 So when you guys update base image to newer version we only need to change FROM... in ur Dockerfile?

**Comment by bparees** [comment]
@Dec- yes if you want additional tools included in the image (and assuming you can't convince us to just add those tools to the image because they are common enough that everyone would benefit from having them), this is the right approach.
