### ISSUE TITLE
Add option for emptyDir volume and mountPath

### ISSUE THREAD

**Issue by rcwwilliams** [sclorg/s2i-nodejs-container#151]
It would be great if the template could include an optional emptyDir volume and mountPath rather than having to add them by editing a deployment config YAML.

This is particularly useful for log files being able to persist after container restarts.

Thanks.

**Comment by phracek** [comment]
Sorry, we do not have capacity to fix this issue. In case you really need it or if it is still valid please re-open this issue.

@rcwwilliams In case you really need it or if it is still valid please re-open this issue.
