### ISSUE TITLE
Generate configuration for react applications on node.js

### ISSUE THREAD

**Issue by chargio** [sclorg/s2i-nodejs-container#171]
Trying to run an application with node.js and React with typescript does not work.

The application is running, and pointing to the port 8080, and you can curl localhost and 0.0.0.0, but there is no response when connecting through the service.

**Comment by omron93** [comment]
> there is no response when connecting through the service.

What IP is service pointing to? Are you connecting outside of OpenShift?

**Comment by chargio** [comment]
I used the template directly.

**Comment by chargio** [comment]
The service and the router are those of the template.

`oc rsh pod-name`

Inside the container

`curl 0.0.0.0:8080`  returns "no javascript enabled" page
`curl localhost:8080`will do the same
`curl $WEB_SERVICE_HOST:$WEB_SERVICE_PORT` will timeout, same behaviour than connecting to the route or to the service from another host in the cluster. I can connect from the pod to the API host

**Comment by phracek** [comment]
Is this issue still valid? We do not have resources to fix it. The issue is 'stale'. Feel free to re-open it and file PR.
