### ISSUE TITLE
Add image for Linux Alpine

### ISSUE THREAD

**Issue by eduardomourar** [sclorg/s2i-nodejs-container#177]
I have made some modifications to use the alpine from official node docker (see fork [here](https://github.com/eduardomourar/s2i-node-alpine)). The question is if this is relevant to the upstream project. If so, I might need some help to make everything work (make, etc) with every OS.

**Comment by torsava** [comment]
Hi @eduardomourar,
thanks for opening an issue for this!

I've tried taking a look at the size comparison between the alpine based image and the standard centos7 based one. As far as I understand, in your `eduardomourar/s2i-node-alpine` image is the `nodejs-4-centos7` so I compared those:

    docker.io/eduardomourar/s2i-node-alpine           latest              eb5ab9cf631d        2 hours ago         495 MB
    docker.io/centos/nodejs-4-centos7                 latest              ce9dc9139d54        7 days ago          535 MB

Thus I'm getting a size shrinking from 535 MB to 495 MB, or about 7.5%. Does this look correct?

**Comment by eduardomourar** [comment]
@torsava yes, you are right. This was my first try at it, so I guess we have room to improve the size of the alpine image with nodejs (there are some packages that can be remove after everything has been installed). I am open to suggestions.

**Comment by torsava** [comment]
@eduardomourar Since these requests for more bases are multiplying (Alpine, centos6, OL, ...), we've discussed this issue with the other maintainers and we sadly don't think it's feasible for us to maintain additional variants. That being said, thank you for opening the issue and offering to help!
