### ISSUE TITLE
Support for FB create-react-app

### ISSUE THREAD

**Issue by vnugent** [sclorg/s2i-nodejs-container#185]
Is there a way to customize how node app is launched? For apps created with FB `create-react-app` I'd like to create an image with `npm run build` and serve contents from the `./build` dir.  At the moment when the pod starts, the app is built again with `npm start`,

**Comment by omron93** [comment]
> Is there a way to customize how node app is launched?

You can add your own `.s2i/bin/run` script into source code of our app. [1] Probably the most safest way is to copy https://github.com/sclorg/s2i-nodejs-container/blob/master/8/s2i/bin/run and change it to your needs.

@kasicka You understand it more. Does it make sense to add this somehow in our `run` script?


[1] https://blog.openshift.com/override-s2i-builder-scripts/

**Comment by phracek** [comment]
Is this issue still valid? We do not have resources to fix it. The issue is 'stale'. Feel free to re-open it and file PR.
