### ISSUE TITLE
Example for nodejs 8.9 LTS version

### ISSUE THREAD

**Issue by weilip1803** [sclorg/s2i-nodejs-container#195]
The current example which uses nodejs version 8.6 is not stable. After repeated use of the builder image,
it give a gives a npm ERR! code Z_BUF_ERROR when install. Really hope to have a Long Term support version example. Thanks.

**Comment by pkubatrh** [comment]
Hi @weilip1803 

What example are we talking about here? Also please be aware that incremental s2i builds (as discussed in https://github.com/sclorg/s2i-nodejs-container/pull/182) are currently not supported.

**Comment by phracek** [comment]
@weilip1803 Can you please provide deep description about example? Otherwise we will close this issue as NodeJS 8.6 is not supported at all.

**Comment by phracek** [comment]
This version reached EOL. Closing this issue. Feel free to re-open it in case it is still valid in the newer versions.
