### ISSUE TITLE
Support Incremental S2I Builds

### ISSUE THREAD

**Issue by adambkaplan** [sclorg/s2i-nodejs-container#203]
Downloads from NPM (or NPM proxy) can take a significant amount of time depending on the complexity of the Node app. Allowing Node s2i builds to cache and restore `/node_modules` could significantly improve build times.

See https://github.com/openshift/source-to-image#incremental-builds on the s2i requirements.

**Comment by pkubatrh** [comment]
https://github.com/sclorg/s2i-nodejs-container/pull/201
