### ISSUE TITLE
What explicit Node version is being installed?

### ISSUE THREAD

**Issue by kbradl16** [sclorg/s2i-nodejs-container#225]
How do I know we get Node v10.16.0, Node v10.17.0, or Node v10.18.0?

It's important because I need to know if I am able to use features added from a minor version or patch fix.

Example:
![image](https://user-images.githubusercontent.com/3843423/71196017-210ca080-225d-11ea-9dcc-e5408196cb1f.png)
- https://nodejs.org/docs/latest-v10.x/api/all.html

**Comment by pkubatrh** [comment]
Hi @kbradl16, sorry for the late response.

you can check the version inside the image by asking the node binary:
```
# docker run --rm -ti rhscl/nodejs-10-rhel7 bash -c "node --version"
v10.16.3
```

For rhel8:
```
# docker run --rm -ti ubi8/nodejs-10 bash -c "node --version"
v10.16.3
```
