### ISSUE TITLE
CentOS7 Node12? How?

### ISSUE THREAD

**Issue by kbradl16** [sclorg/s2i-nodejs-container#227]
How do I use CentOS 7 with Node12? I don't see Node12 on the mirror list http://mirror.centos.org/centos/7/sclo/x86_64/rh/ Is there another place to look?

Maybe I'm confused. How does this project/repo fit into the equation?

**Comment by pkubatrh** [comment]
Hi @kbradl16 

currently the nodejs 12 rpms are in the [candidate repositories](https://cbs.centos.org/repos/sclo7-rh-nodejs12-rh-candidate/x86_64/os/). They need to stay there for a while before they can be moved to regular repos.

>Maybe I'm confused. How does this project/repo fit into the equation?

This github repository provides sources for container images that are using the nodejs SCLs (for centos7/rhel7) and modules (rhel8/fedora).

Hope this helps!

**Comment by kbradl16** [comment]
@pkubatrh thanks, this was extremely helpful!

So to clarify the SCL page will update when the [candidate repositories](https://cbs.centos.org/repos/sclo7-rh-nodejs12-rh-candidate/x86_64/os/) get "merged" in? And what does a while mean? Is there a way to monitor the time until it's available?

**Comment by pkubatrh** [comment]
@khardix Do you know the answer to above?

**Comment by khardix** [comment]
@kbradl16 I have just created a [PR][] that should enable pushing the collections to the mirrors. Once it's merged, the collection should be available in a few days.

[PR]: https://git.centos.org/centos/cbs-content-control/pull-request/25

**Comment by kbradl16** [comment]
@khardix @pkubatrh I see the [nodejs12 release Jenkins build](https://ci.centos.org/job/SCLo-pkg-rh-nodejs12-rh-C7-release-x86_64/) is now passing. What's the next steps? What happens in the next few days?

**Comment by khardix** [comment]
> @khardix @pkubatrh I see it's merged and the [nodejs12 release Jenkins build](https://ci.centos.org/job/SCLo-pkg-rh-nodejs12-rh-C7-release-x86_64/) is now passing. What's the next steps? What happens in the next few days?

There is a synchronization script that runs regularly which copies the RPMs from the build system to the public repository. After that, it may take a while until the changes propagate to all other public mirrors.

**Comment by kbradl16** [comment]
Did the sync script run? Any links to it?

**Comment by khardix** [comment]
@kbradl16 The process is documented in [section of CentOS SIG guide](https://wiki.centos.org/SIGGuide/Content/Mirror). Sadly, no links to the actual script.

From cursory glance at the mirrors today, the collections still are not there – so it may be worthwhile to ask on `#centos-devel` on freenode (IRC), or on centos-devel@centos.org mailing list.

**Comment by kbradl16** [comment]
@khardix I asked. I did just notice that the mirror build was failing https://ci.centos.org/job/SCLo-pkg-rh-nodejs12-rh-C7-mirror-x86_64/

any ideas how that ties into the process?

**Comment by khardix** [comment]
@kbradl16 The mirror job checks the packages on mirrors; in other words, once it is green, the packages are (should be) publicly available and installable. You should be able to use the status of this job in place of the mirror refresh :wink:

**Comment by khardix** [comment]
@kbradl16 I can see that the rh-nodejs12 packages have made the journey to the mirrors at last :tada: Are they working for you and can we thus close this issue?

**Comment by kbradl16** [comment]
I don't see node12 showing up on the softare collections page. Is this an issue? https://www.softwarecollections.org/en/scls/?search=nodejs

**Comment by khardix** [comment]
> I don't see node12 showing up on the softare collections page. Is this an issue?

Not really; It just means I did not yet find the time to prepare the announcements and add the entries to scl.org.

**Comment by intirix** [comment]
I was able to do a yum install, so it looks like it is working.  Thanks a lot for your work!

**Comment by kbradl16** [comment]
Hi, sorry forgot to submit my comment. It worked for me too! Yay! Thanks! 

I have one last question. It seems like node 12.10 is the version available. How do we get the latest version of node 12 installed?

**Comment by khardix** [comment]
@kbradl16 Not all version of the Node interpreter are packaged; the repository should contain the latest packaged one. If you want to always have the newest version released by upstream, I'm afraid you would have to build it yourself.
