### ISSUE TITLE
Error: certificate has expired

### ISSUE THREAD

**Issue by svettwer** [sclorg/s2i-nodejs-container#242]
Hi :wave: 

We're using centos/nodejs-12-centos7 for an s2i build of our application. Since last weekend (01.06.20) we're receiving messages about expired certificates when performing rest calls using `node-fetch`.

```
could not perform health check. { FetchError: request to <MY_URL> failed, reason: certificate has expired
    at ClientRequest.<anonymous> (/opt/app-root/src/server/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'request to <MY_URL> failed, reason: certificate has expired',
  type: 'system',
  errno: 'CERT_HAS_EXPIRED',
  code: 'CERT_HAS_EXPIRED' }
```

A first analysis has shown that the issue does not occur when starting the application on the development machine without a previous s2i build. When building the application using s2i cli, the issue is reproducible and the "certificate has expired" error shows up. That led me to the assumption that the container might be the cause, even if I currently don't understand how this could be possible. From my understanding, the root cause should be an expired certificate on the server that we're calling and not something from the container.
Funny enough: calling another service for a health check with `node-fetch` works perfectly fine. This would also confirm the server side certificate expiration.
I'm just curious why this is only reproducible in the container. 

Any hint would be highly appreciated. I'll continue my research and keep you posted in case I find a solution.

Edit: `NODE_TLS_REJECT_UNAUTHORIZED` is not set to `0`

**Comment by svettwer** [comment]
I've also checked the server certificate. It is up to date and valid.

**Comment by ppisar** [comment]
Could you show us the URL?

Recently a big certificate authority experienced an certificate experiation.
It mitigated the issue by reissuing the root certiciate with the same key
but a prolonged life time.

However, it does not prevent the users to get the error untill they update the
certificate authority certificate bundle (ca-certificates RPM package in RHEL
systems), or until the servers stop sending the expired certificate in TLS
handshakes (requires updating the bundle on the servers). Morover, a bug in
GnuTLS library was found that prevents from verifiyng a server certificate if
the library encounres the expired authority certificate (clients must upgrade
the GnuTLS library). Also a similar bug exists in old version of OpenSSL
library (clients must upgrade the OpenSSL library).

Maybe are also affected. But without sharing us the URL, we cannot reproduce
your issue.

-- Petr

**Comment by svettwer** [comment]
I also thought about that issue but was unable to reconstruct it. Unfortunately I cannot provide the URL. 

When performing a `wget`from the container I receive:
```
--2020-06-04 11:02:48--  <URL>
Resolving <URL>
Connecting to <URL>... connected.
ERROR: cannot verify <URL>'s certificate, issued by '/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA':
  Issued certificate has expired.
To connect to <URL> insecurely, use `--no-check-certificate'.
```

This points exactly to the expired cert issue, if I understood it correctly. That it worked locally might be caused by an updated OpenSSL version that is able to build up the cert chain without using expired cert. I'll get in contact with the server admins so that the certificates are cleaned up.
On the other hand: That this issue is a show stopper on the container might indicate an outdated certificate bundle or an outdated GnuTLS/OpenSSL lib installed, right?
I hate that it is not possible for me to provide the URL so that you are able to investigate this and maybe mitigate the issue on the container side. Maybe it is possible for me to dig a little deeper myself and provide further hints.

**Comment by ppisar** [comment]
You can reproduce it with wget. What cryptographic library does your wget use?

# wget --version
GNU Wget 1.14 sestaven na systému linux-gnu.

+digest +https +ipv6 +iri +large-file +nls +ntlm +opie +ssl/openssl

This means OpenSSL. What certificats does the server send?

# openssl s_client -connect HOST:PORT -showcerts

Is one of them expired? Then ask the server admin to fix the server.

If they are not expired, can "openssl verify ..." command verify each of the
certificates? Check them in the order from a root to a client certificate.

If some of them cannot be verified, then you should see a reason for that
(a missing or expired CA certificate). If that's so, check when the
ca-certificates package was updated (rpm -q ca-certificates, rpm -q
--changelog ca-certificates).

If it is not up-to-date, you need to get a newer container image (or update
the package yourself).

-- Petr

**Comment by svettwer** [comment]
Hi :wave: 

Thanks a lot for your support.
We figured out that the expired comodo intermediate certificate was still transmitted to the client. So we're about to fix that on the server side. Thanks for helping me to identify the expired certificate. I've not that much experience on certificates and it was great to learn about it! Many Kudos! :clap: 

In addition, the ca-certificates version in  the `centos/centos7:latest` container is `2019.2.32-76`. Unfortunately, no newer version is available. 
```
yum install ca-certificates
[...]
Package ca-certificates-2019.2.32-76.el7_7.noarch already installed and latest version
```

We'll try to fix the issue by cleaning up the sent certificates. An update on the ca-certificates package and libcrypto would be nice but as far as I can see the container is up to date with what is available via yum. 
From my point of view, this issue could be closed if you don't have any open remarks or questions.

Thanks again for your support! :beers:
