### ISSUE TITLE
node-rdkafka failed with gcc-4.8

### ISSUE THREAD

**Issue by phracek** [sclorg/s2i-nodejs-container#285]
Fix in node-rdkafka works only with gcc-8 available on RHEL8 and not with gcc-4.8 available on RHEL7.

It would be nice to skip this test from RHEL7, CentOS7.

Upstream PR https://github.com/Blizzard/node-rdkafka/pull/892/files.
The upstream issue for fixing also for gcc-4.8 https://github.com/Blizzard/node-rdkafka/issues/910

**Comment by phracek** [comment]
The test should be suppressed for  CentOS 7 and RHEL7 is https://github.com/sclorg/s2i-nodejs-container/blob/master/test/run#L590

Upstream kafka issue is here: https://github.com/Blizzard/node-rdkafka/issues/910
WDYT?

@pkubatrh @hhorak

**Comment by hhorak** [comment]
Idea mentioned on RHSCL containers images meeting April 27 -- we might consider installing newer gcc collection. We didn't discuss it properly, so further analysis whether it's a good idea is needed.

**Comment by phracek** [comment]
It looks like the problem was already fixed and we did not have this issue now. So closing it. Feel free to reopen it.
