### ISSUE TITLE
nodejs:14-ubi8 Failing due to upstream removal of binding release binary reference in image

### ISSUE THREAD

**Issue by aenertia** [sclorg/s2i-nodejs-container#289]
Using source application deployment strategy and the nodejs14-ubi image. A call to pull the release tag of a now removed nodejs-binding-86-83

This means s2i deploys relying on the nodejs14 image are currently failing.

Please fix

![image](https://user-images.githubusercontent.com/286383/133957064-20d85cef-8e8b-4894-bfd3-5459cb7bbdd1.png)

**Comment by pkubatrh** [comment]
Hi @aenertia thanks for the report.
Do I understand it correctly that the s2i build is failing because node-sass upstream removed one of their releases? If so I do not think this is something we can help with.

**Comment by pkubatrh** [comment]
Closing for now, please reopen if we can move this forward somehow
