### ISSUE TITLE
Fedora 32 and 33 EOL

### ISSUE THREAD

**Issue by frenzymadness** [sclorg/s2i-nodejs-container#301]
Fedora 32 is unsupported since 2021-05-25 and Fedora 33 is going to lose support tomorrow. It might make sense to document it somewhere or remove the docker files based old Fedora releases.

This is not a problem for nodejs 10 and older because they are marked as deprecated in their readmes.

**Comment by phracek** [comment]
Tests are failing for these reasons, in my opinion.

**Comment by phracek** [comment]
Closed in favor of https://github.com/sclorg/s2i-nodejs-container/pull/323
