### ISSUE TITLE
QUESTION: v18 image availability in registry

### ISSUE THREAD

**Issue by kaufmo** [sclorg/s2i-nodejs-container#355]
Hi, do you know when is the ubi8/ubi9 nodejs18 image available through the registry.access.redhat.com?

**Comment by mhdawson** [comment]
@kaufmo a ubi8 nodejs18 container will be available some time after the community makes nodejs 18 LTS in October.  The exact timing depends on how that timing lines up with RHEL point releases but I think we are hoping for some time in December.

Until then we have unofficial images in quay that can be used for early testing - https://quay.io/repository/sclorg/nodejs-18-c8s. These are based on centos stream 8.

**Comment by kaufmo** [comment]
@mhdawson thx for your answer :+1: then we will wait for the image. Our policy is to use only official images

**Comment by mhdawson** [comment]
@kaufmo thanks for confirming. Is it ok if I close this issue?

**Comment by kaufmo** [comment]
yeah its ok :+1:
