### ISSUE TITLE
docker build with Dockerfile failed

### ISSUE THREAD

**Issue by jameswangjz** [sclorg/s2i-nodejs-container#373]
perl-threads.x86_64 0:1.87-4.el7                                              
  perl-threads-shared.x86_64 0:1.43-6.el7                                       
  zlib-devel.x86_64 0:1.2.7-20.el7_9                                            

Dependency Updated:
  glibc.x86_64 0:2.17-326.el7_9           glibc-common.x86_64 0:2.17-326.el7_9  
  krb5-libs.x86_64 0:1.15.1-55.el7_9      libcom_err.x86_64 0:1.42.9-19.el7     
  libgcc.x86_64 0:4.8.5-44.el7            libstdc++.x86_64 0:4.8.5-44.el7       
  openssl-libs.x86_64 1:1.0.2k-25.el7_9   zlib.x86_64 0:1.2.7-20.el7_9          

Complete!
package rh-nodejs16 is not installed
package rh-nodejs16-npm is not installed
package rh-nodejs16-nodejs-nodemon is not installed
The command '/bin/sh -c yum install -y centos-release-scl-rh &&     MODULE_DEPS="make gcc gcc-c++ git openssl-devel" &&     INSTALL_PKGS="$MODULE_DEPS rh-nodejs${NODEJS_VERSION} rh-nodejs${NODEJS_VERSION}-npm rh-nodejs${NODEJS_VERSION}-nodejs-nodemon nss_wrapper" &&     ln -s /usr/lib/node_modules/nodemon/bin/nodemon.js /usr/bin/nodemon &&     yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     node -v | grep -qe "^v$NODEJS_VERSION\." && echo "Found VERSION $NODEJS_VERSION" &&     yum -y clean all --enablerepo='*'' returned a non-zero code: 3
[root@agc 16]#

**Comment by jameswangjz** [comment]
the whole info is here: https://note.youdao.com/s/2BxStwGh

**Comment by pkubatrh** [comment]
Hi, this is expected. There is no Nodejs in RHEL7 or Centos7 and no plans to build it afaik. You can see the list of supported versions for each release in the README file (https://github.com/sclorg/s2i-nodejs-container/blob/master/README.md)
