### ISSUE TITLE
clients: Pino tests are failing

### ISSUE THREAD

**Issue by lholmquist** [sclorg/s2i-nodejs-container#381]
the pino tests are having failures on these platforms in the testing farm:

Fedora Node 18
Fedora Node 16
RHEL9 - Unsubscribed host - node 16

cc @lholmquist @mhdawson

**Comment by pkubatrh** [comment]
Discussed the failure of pino test case on the nodejs meeting for a bit, we have decided to try and pin a specific version of the module and test with that.
If we figure out the tests are still as flaky as they were before this change, let's focus on making the upstream pino test suite more hardened to failures.

**Comment by phracek** [comment]
What about having two tests? First one will be freezed 'pino', 'faas' that should pass always. The other test will use the latest upstream versions, it will be marked as unstable in case of failure. See PR here: https://github.com/sclorg/s2i-nodejs-container/pull/342

**Comment by mhdawson** [comment]
@phracek that sounds reasonable. One question I had is if the pino tests are flaky or have just never passed on RHEL 9?

**Comment by phracek** [comment]
This can be closed based on the Nightly build tests.
