### ISSUE TITLE
Permission errors when using Dockerfile instructions

### ISSUE THREAD

**Issue by jramcast** [sclorg/s2i-nodejs-container#396]
### Container platform

OCP 4, Podman/Docker

### Version

`ubi8/nodejs-18`
`ubi8/nodejs-18-minimal` 
`ubi9/nodejs-18`
`ubi9/nodejs-18-minimal` 

### OS version of the container image

RHEL 8, RHEL 9

### Description

Following the Dockerfile instructions from https://github.com/sclorg/s2i-nodejs-container/blob/master/18/README.md#31-to-use-your-own-setup-create-a-dockerfile-with-this-content results in this error when running `podman build`

```
STEP 1/4: FROM registry.access.redhat.com/ubi8/nodejs-18
STEP 2/4: ADD . .
--> Using cache f918b33f480dbc86707722c82648e5644aed889f098c454e3270e29b980250d0
--> f918b33f480
STEP 3/4: RUN npm install
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /opt/app-root/src/package-lock.json
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, open '/opt/app-root/src/package-lock.json'
npm ERR!  [Error: EACCES: permission denied, open '/opt/app-root/src/package-lock.json'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/opt/app-root/src/package-lock.json'
npm ERR! }
```

If I use `npm ci` instead of `npm install`, then Podman builds the image. If I push that image to a registry, quay.io for example, and then try to deploy the image with `oc new-app --docker-image=quay.io...`, the application pod fails:

```
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /opt/app-root/src/.npm/_cacache
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000700000:0 "/opt/app-root/src/.npm"

npm ERR! Log files were not written due to an error writing to the directory: /opt/app-root/src/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
```

I have also tried to apply the instructions given in the [Node.js 18 minimal overview page](https://catalog.redhat.com/software/containers/ubi9/nodejs-18-minimal/62e8e919d4f57d92a9dee838), under section `3.1`, which uses a multistage dockerfile. The same two problems happen.

NOTE: this is maybe related to https://github.com/npm/cli/issues/5114

### Reproducer

To reproduce the error in OCP, you can use this command: `oc new-app --docker-image=quay.io/jramcast/do288-images-ubi-hello:1.0.0`

**Comment by jramcast** [comment]
I can replicate the problem by running the build locally, with  `podman build`, using these tree:

```
.
├── app-src
│   ├── index.js
│   ├── package.json
│   └── package-lock.json
└── Containerfile
```

The contents of the Containerfile are:
```
FROM registry.access.redhat.com/ubi8/nodejs-18

# Add application sources
ADD app-src .

# Install the dependencies
RUN npm install

# Run script uses standard ways to run the application
CMD npm run -d start
```

And the permission of the app source files are:

```
-rw-r--r--. 1 myuser myuser 1031 Jun 14 17:50 index.js
-rw-r--r--. 1 myuser myuser  199 Jun 14 15:42 package.json
-rw-r--r--. 1 myuser myuser  191 Jun 14 15:42 package-lock.json
```

So running  `podman build . -t my-node-test` results in:

```
STEP 1/4: FROM registry.access.redhat.com/ubi8/nodejs-18
STEP 2/4: ADD app-src .
--> Using cache 65507d481756f798485699a2f88219cd6495ef78b5b07203122ecae0710ef691
--> 65507d48175
STEP 3/4: RUN npm install
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /opt/app-root/src/package-lock.json
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, open '/opt/app-root/src/package-lock.json'
npm ERR!  [Error: EACCES: permission denied, open '/opt/app-root/src/package-lock.json'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/opt/app-root/src/package-lock.json'
npm ERR! }
npm ERR! 
```

**Comment by pkubatrh** [comment]
Can confirm I can replicate the issue now when I generate a `package-lock.json` file and `chmod 644` it.

I guess npm needs write access to the lock file? From what I can see locally, the source files that get added are set up to be owned by 0:0, but the container image is run by 1001:0 by default (or random uid and root gid in OCP), so with 644 the write access is missing for group. With 664 it works as expected.

In general I would recommend keep the files inside the image group writeable (those that you expect to write to), as that is how the image is designed to work with OCP's runtime UID randomization.

**Comment by jramcast** [comment]
Thanks @pkubatrh for taking some time to look at this! 

Yeah, my problem is originated by group permissions. I am using a restrictive `umask` config: `002`, which means that, when I create a file or a directory in my computer, they won't be writable by the group, by default. As you say, granting write permissions to the group (chmod 664) solves my first issue - the one with the local podman build and the package.lock file. 

Now, the second issue is different, because it's related to how the NPM container runs on OpenShift.
* If I use [the Dockerfile.s2i example](https://github.com/sclorg/s2i-nodejs-container/blob/master/examples/from-dockerfile/Dockerfile.s2i), my containers run just fine. I see that the `s2i/bin/assemble` script fixes the permissions so I guess that's the reason why I don't face problems in this case
* If I use the [non-s2i Dockerfile example](https://github.com/sclorg/s2i-nodejs-container/blob/master/examples/from-dockerfile/Dockerfile) (with nodejs-16), then pods fails with the `opt/app-root/src/.npm/_cacache`EACCESS error. Looking into the Container file, this is what I see:
```
drwxr-xr-x. 3 1001 root   19 Jun 16 12:55 .npm
```
It appears the `RUN npm install` instruction is creating this directory without write permissions for the root group, so when the container runs on OpenShift, NPM does not have write access to this directory (which apparently is required when running `npm start`).

One way to solve this problem is adding `rm -rf .npm` to the Dockerfile, so maybe we might consider adding that to the instructions for non-s2i Dockerfiles.

**Comment by pkubatrh** [comment]
We discussed how to document this behavior when unexpected permissions are encountered during the build of the image and decided that rather than recommending removing the `.npm` directory (while likely safe) it is better to fix the permissions issues the same way as the s2i version of the example does - through the use of the `fix-permissions` script.

I will follow up with a PR that adds a comment about this inside the Dockerfile (`fix-permissions` will not be called by default) so the user has a hint at how to mitigate permission issues when using the examples.

**Comment by jramcast** [comment]
Thank you @pkubatrh ! That makes a lot of sense actually. FYI, in my case, the permissions issue did not occur at build time, but at execution time, on OpenShift, when the container runs `npm start`.

**Comment by pkubatrh** [comment]
Right, but I expect that would be fixed if you called `fix-permissions` after the `.npm` directory gets initialized at build. Which means you would have to move the `fix-permissions` call in the Dockerfile example a bit, but at least now it should be obvious what you can do to correct permission problems.

Closing the issue now that we have some documentation in place, but feel free to reopen if you feel like there is something more that needs to be done.
