### ISSUE TITLE
What's the typical delay between a NodeJS minor version release to its availability here?

### ISSUE THREAD

**Issue by Amndeep7** [sclorg/s2i-nodejs-container#417]
### Container platform

Podman/Docker

### Version

18.19.x and 20.10.x

### OS version of the container image

RHEL 8

### Description

18.19.x and 20.10.x were released in mid-late November.  It is currently mid-December, but the containers only have 18.18.x and 20.9.x available.  How large is the typical delay between the minor version release and its availability within a container?

Thanks for the hard work!

**Comment by hhorak** [comment]
Thanks for the answer. The releases of the RHEL container images with Node.js updates are driven by CVEs affecting the images, with a specific focus on their severity, and customer demand that gets to the engineering team through the Red Hat Customer Portal (https://access.redhat.com).

While it differs a lot, to have some idea about how often it is, I'd say that sometimes it's a couple of weeks, but sometimes a few (3-4) months, but please, don't take it as anything set in stone or promissed.

If there is a specific need for a new version, I'd encourage to contact the Red Hat Customer Support on the page mentioned above. Hope this helps.
