### ISSUE TITLE
Provide this for LTS and latest NodeJS too

### ISSUE THREAD

**Issue by temsa** [sclorg/s2i-nodejs-container#86]
Hi!

Years have passed, NodeJS-0.10 is far far away now, maybe openshift could support at least LTS version (4.3.1) by default, if not latest one (currently 5.7.0), or better: both ?

Or maybe better than better, support a custom version through an environment variable ( and/or `package.json` referenced version ), like do some cartridges on github ?

**Comment by temsa** [comment]
example custom version cartridge : https://github.com/icflorescu/openshift-cartridge-nodejs

**Comment by bparees** [comment]
Are you asking for this for openshift v2 (cartridge) or openshift v3 (image)?

v2 isn't going to happen, for v3 we do have plans to add a new nodejs4.x image in the very near future, our SCL team is working on it.

**Comment by temsa** [comment]
In fact, both of them, yet this one  was specifically targeted at openshift
v3 ;)

2016-02-24 15:30 GMT+01:00 Ben Parees <notifications@github.com>:

**Comment by ryanj** [comment]
@temsa Feel free to give these images a try: https://github.com/ryanj/origin-s2i-nodejs#versions

**Comment by hhorak** [comment]
This will be addressed by #96, once it is merged.

**Comment by hhorak** [comment]
NodeJS 4.4 is now available.
