### ISSUE TITLE
running `make test` on mac gives an error

### ISSUE THREAD

**Issue by alberttwong** [sclorg/s2i-nodejs-container#92]
```
Alberts-MacBook-Pro:sti-nodejs alwong$ make test
SKIP_SQUASH=0 VERSIONS="0.10" OS=centos7 VERSION= BASE_IMAGE_NAME=nodejs OPENSHIFT_NAMESPACES="0.10" TAG_ON_SUCCESS= TEST_MODE=true hack/build.sh
hack/build.sh: line 73: conditional binary operator expected
```

**Comment by alberttwong** [comment]
https://github.com/openshift-s2i/s2i-aspnet/issues/7

**Comment by phracek** [comment]
Building containers on Mac systems are not supported. There are several bash issues discrovered by migration to Mac environment. If you are still insterested please file a pull request against repository https://github.com/sclorg/container-common-scripts.

There is no plan to migrate building workflow to Mac OS. Sorry.
